name: Update Prices

# Запуск по расписанию (каждый час)
on:
  schedule:
    - cron: '0 * * * *' # каждый час
  workflow_dispatch: # возможность запускать вручную

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Устанавливаем Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # 3. Устанавливаем зависимости (если нужны)
      - name: Install dependencies
        run: npm install

      # 4. Запускаем конвертер
      - name: Run convert.js
        run: node scripts/convert.js

      # 5. Коммитим изменения
      - name: Commit updated JSON
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add public/spotprices.json
          git commit -m "Auto update prices" || echo "No changes to commit"

      # 6. Пушим обратно в main
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
